apiVersion: v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: vinay
spec:
  # 1 Pod should exist at all times.
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: ravi2krishna/login-2429
        ports:
        - containerPort: 80