apiVersion: v1
kind: Pod
metadata:
  name: rajesh
spec:
  containers:
   - name: nginx
     image: nginx
     ports:
     - containerPort: 80
   - name: node-fe
     image: rajeshgandham123/node-fe
     ports:
     - containerPort: 8080