apiVersion: v1
kind: Replicaset
metadata:
  name: vinay
spec:
  replicas: 1
  selector:
   matchLabels:
    app: nginx
  template:
   metadata:
    labels:
    app: nginx
  spec:
   container:
    ports:
     containerPort: 80
